@localBase = http://localhost:8000
@deployedBase = https://sep4.edproduction.dev

### Local: hello
GET {{localBase}}/
Accept: application/json

### Local: db-check
GET {{localBase}}/db-check
Accept: application/json

### Local: focus prediction
POST {{localBase}}/predict
Content-Type: application/json

{
  "temperature": 22,
  "humidity": 45,
  "co2Level": 650,
  "lightLevel": 550,
  "noiseLevel": 42
}

### Deployed: hello
GET {{deployedBase}}/
Accept: application/json

### Deployed: db-check
GET {{deployedBase}}/db-check
Accept: application/json
