flowchart TD
MAIN[main.c]
MAIN --> SERVER_H["&lt;&lt;interface&gt;&gt;<br/>server_api"]
SERVER_H --> SERVER_C[server_apiImpl]
SERVER_C --> HTTP_H["&lt;&lt;interface&gt;&gt;<br/>wifi_http"]
HTTP_H --> HTTP_C[wifi_httpImpl]
HTTP_H --> WIFI_H["&lt;&lt;interface&gt;&gt;<br/>wifi"]
WIFI_H --> WIFI_C[wifiImpl]
MAIN --> UART_STDIO_H["&lt;&lt;interface&gt;&gt;<br/>uart_stdio"]
UART_STDIO_H --> UART_STDIO_C[uart_stdioImpl]
UART_STDIO_H --> UART_H["&lt;&lt;interface&gt;&gt;<br/>uart"]
MAIN --> UART_H
WIFI_H --> UART_H
UART_H --> UART_C[uartImpl]
UART_H --> RINGBUFFER_H["&lt;&lt;interface&gt;&gt;<br/>ringbuffer"]
RINGBUFFER_H --> RINGBUFFER_C[ringbufferImpl]
MAIN --> DHT_H["&lt;&lt;interface&gt;&gt;<br/>dht11"]
DHT_H --> DHT_C[dht11Impl]
MAIN --> CO2_H["&lt;&lt;interface&gt;&gt;<br/>co2"]
CO2_H --> CO2_C[co2Impl]
CO2_C --> UART_H
MAIN --> LIGHT_H["&lt;&lt;interface&gt;&gt;<br/>light"]
LIGHT_H --> LIGHT_C[lightImpl]
LIGHT_H --> ADC_H["&lt;&lt;interface&gt;&gt;<br/>adc"]
ADC_H --> ADC_C[adcImpl]
MAIN --> BUTTON_H["&lt;&lt;interface&gt;&gt;<br/>button"]
BUTTON_H --> BUTTON_C[buttonImpl]
MAIN --> TIMER_H["&lt;&lt;interface&gt;&gt;<br/>timer"]
TIMER_H --> TIMER_C[timerImpl]
MAIN --> DISPLAY_STATUS_H["&lt;&lt;interface&gt;&gt;<br/>display_status"]
DISPLAY_STATUS_H --> DISPLAY_STATUS_C[display_statusImpl]
MAIN --> DISPLAY_H["&lt;&lt;interface&gt;&gt;<br/>display"]
DISPLAY_STATUS_C --> DISPLAY_H
DISPLAY_H --> DISPLAY_C[displayImpl]
SERVER_C --> BUZZER_H["&lt;&lt;interface&gt;&gt;<br/>buzzer"]
BUZZER_H --> BUZZER_C[buzzerImpl]