@startuml
title State Machine: Student
!include https://raw.githubusercontent.com/fredoslav2004/MinimalThemePUML/refs/heads/main/minimal-theme.puml
state Not_studying
state studying

[*] --> Not_studying
Not_studying --> studying : startStudying
studying --> Not_studying : stopStudying
@enduml
