@startuml Student_StateMachine
' State Machine for Student
[*] --> Not_studying
studying --> knowsNoiseLevel : CheckNoiseLevel
studying --> knowsLightLevel : CheckLightLevel
studying --> knowsCO2Level : CheckCO2Level
studying --> knowsTemperature : CheckTemperature
studying --> knowsHumidity : CheckHumidity
studying --> knowsDustLevel : CheckDustLevel
@enduml
