@startuml
title Sequence Diagram: ReceiveEnvironmentNotification
actor "Student" as Actor
participant "system" as System

Actor -> System : monitorEnvironment
alt Parameters not optimal
System -> Actor : sendNotification
end
@enduml
