@startuml
title System Sequence Diagram: ManageCalendarEvents
!include https://raw.githubusercontent.com/fredoslav2004/MinimalThemePUML/refs/heads/main/minimal-theme.puml
actor "Student" as Actor
participant "system" as System

Actor -> System : createCalendarEvent(title, note, startTime, endTime)
System -> Actor : confirmEventCreated
@enduml
