@startuml
title Sequence Diagram: ReceiveEnvironmentNotification
actor "Student" as Actor
participant "system" as System
participant "Student" as Student

Actor -> System : monitorEnvironment
alt Parameters not optimal
System -> Student : sendNotification
end
@enduml
