@startuml StudyHelper_CheckCO2Level_SSD
title System Sequence Diagram: CheckCO2Level
actor "Student" as Actor
participant "@sys" as System
Actor -> System : Student requests current CO2 level
Actor -> System : requestCO2Data
Actor -> System : System returns CO2 concentration in ppm
@enduml
