@startuml
title System Sequence Diagram: ReceiveStudentEnvironmentAlert
!include https://raw.githubusercontent.com/fredoslav2004/MinimalThemePUML/refs/heads/main/minimal-theme.puml
actor "Student" as Actor
participant "system" as System

Actor -> System : monitorActiveSessionConditions
alt predictedStudyQuality == 1
System -> Actor : notifyCriticalStudyConditions
end
@enduml
