### MAL API Testing

@baseUrl = http://localhost:8000

### 1. Root Endpoint
GET {{baseUrl}}/
Accept: application/json

### 2. Database Health Check
GET {{baseUrl}}/db-check
Accept: application/json

### 3. Model Information (shows last training time)
GET {{baseUrl}}/model-info
Accept: application/json

### 4. Machine Learning Prediction
POST {{baseUrl}}/predict
Content-Type: application/json
Accept: application/json

{
    "currentTemperature": 22.0,
    "maxTemp": 24.0,
    "minTemp": 20.0,
    "meanTemp": 21.8
}
