@base = http://localhost:8000

### Local: hello
GET {{base}}/
Accept: application/json

### Local: db-check
GET {{base}}/db-check
Accept: application/json

### Local: predict a focus rating
POST {{base}}/predict
Content-Type: application/json
Accept: application/json

{
  "currentNoise": 40,
  "maxNoise": 45,
  "minNoise": 35,
  "meanNoise": 40
}

### Local: invalid prediction payload returns 422
POST {{base}}/predict
Content-Type: application/json
Accept: application/json

{
  "currentNoise": 40,
  "maxNoise": 30,
  "minNoise": 35,
  "meanNoise": 40
}

### Deployed: hello
GET {{base}}/
Accept: application/json

### Deployed: db-check
GET {{base}}/db-check
Accept: application/json

### Deployed: predict a focus rating
POST {{base}}/predict
Content-Type: application/json
Accept: application/json

{
  "currentNoise": 40,
  "maxNoise": 45,
  "minNoise": 35,
  "meanNoise": 40
}

### Model info: 
GET {{base}}/model-info
Accept: application/json