### MAL API Testing

@baseUrl = http://localhost:8000

### 1. Root Endpoint
GET {{baseUrl}}/
Accept: application/json

### 2. Database Health Check
GET {{baseUrl}}/db-check
Accept: application/json

### 3. Model Information (shows last training time)
GET {{baseUrl}}/model-info
Accept: application/json

### 4. Machine Learning Prediction
POST {{baseUrl}}/predict
Content-Type: application/json
Accept: application/json

{
    "currentNoise": 45.5,
    "maxNoise": 60.2,
    "minNoise": 30.1,
    "meanNoise": 42.8
}
