#!/usr/bin/env python3
import os
import re

def generate_appendices():
    project_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    appendices_dir = os.path.join(project_root, "Documentation", "Appendices")
    report_file = os.path.join(project_root, "Documentation", "ProjectReport", "project-report.md")
    
    if not os.path.exists(appendices_dir):
        print(f"Error: Appendices directory '{appendices_dir}' not found.")
        return
        
    if not os.path.exists(report_file):
        print(f"Error: Project report '{report_file}' not found.")
        return
        
    print("Generating simplified Appendices list (headings & folder descriptions)...")
    
    # 1. Scan Appendices subdirectories
    subdirs = []
    for item in os.listdir(appendices_dir):
        full_path = os.path.join(appendices_dir, item)
        if os.path.isdir(full_path) and not item.startswith("."):
            subdirs.append(item)
            
    # Sort subdirectories numerically by their prefix (e.g. 1.1, 1.2, 2.1, 9.1)
    def get_sort_key(name):
        match = re.match(r"^(\d+)\.(\d+)", name)
        if match:
            return (int(match.group(1)), int(match.group(2)), name)
        return (99, 99, name)
        
    subdirs.sort(key=get_sort_key)
    
    # 2. Build the Appendices Markdown content
    markdown_content = []
    markdown_content.append("# Appendices\n")
    markdown_content.append("<!-- This section is automatically generated by generate_appendices_list.py. Do not edit manually. -->\n")
    markdown_content.append("This section provides a structured overview of the supplementary files, diagrams, contracts, and source code packages submitted as part of the project. All listed folders are included within the final compressed submission package (`.zip`) under the `Appendices/` directory.\n\n")
    
    # Standard descriptions mapping
    descriptions = {
        "1.1 Group Contract": "Contains the formal group contract establishing collaboration guidelines, division of responsibilities, and team rules.",
        "1.1 Project Description": "Contains the approved SEP4 Project Description document outlining the initial project scope, sub-questions, and targets.",
        "1.2 Group Contract": "Contains supplementary group contracts or updates to the primary contract documents.",
        "1.3 Interfacing Contract": "Contains the technical interfacing contract defining communication protocols, endpoints, and JSON schemas between components.",
        "2.1 Requirements": "Contains supplementary requirements documentation, architectural notes, and non-functional specifications.",
        "2.2 Use Cases and SSDs": "Contains use case descriptions, system sequence diagrams (SSDs), activity diagrams, and state transition models.",
        "3.1 Database Schema": "Contains SQL initialization scripts (`01_schema.sql`) for creating database tables, relationships, and indices.",
        "4.1 ML Data Pipeline": "Contains the data flow diagrams and pipeline specifications describing the ingestion and preprocessing model.",
        "4.2 ML Model Evaluation": "Contains machine learning evaluation metrics, model comparison records, and confusion matrices.",
        "4.3 ML Test Results and MLOps": "Contains automated test logs, MLOps requirements, and testing configurations for the prediction service.",
        "5.1 Frontend Wireframes and UI Design": "Contains user interface wireframes, component architecture diagrams, and layout screenshots.",
        "6.1 DevOps and CICD Pipelines": "Contains the continuous integration and delivery (CI/CD) configuration files for GitHub Actions workflows.",
        "6.2 Cloud Architecture and Deployment": "Contains Docker Compose files, Dockerfiles, and deployment blueprints for cloud hosting.",
        "9.1 Source Code": "Contains the complete buildable source code repository of the StudyHelper platform."
    }
    
    for subdir in subdirs:
        # Extract prefix and title
        match = re.match(r"^(\d+\.\d+)\s*(.*)$", subdir)
        if match:
            prefix = match.group(1)
            title = match.group(2)
        else:
            prefix = ""
            title = subdir
            
        markdown_content.append(f"## Appendix {prefix if prefix else ''} — {title}\n\n")
        
        # Get description from mapping or default
        desc = descriptions.get(subdir, f"Supplementary folder containing materials for {title}.")
        markdown_content.append(f"{desc}\n\n")
        markdown_content.append(f"*Folder location in submission:* `Appendices/{subdir}/`\n\n")
        
        # If it is the source code folder, we add component details as well
        if "9.1" in prefix or "source code" in title.lower():
            markdown_content.append("The source repository is organized into the following component packages:\n\n")
            markdown_content.append("- **`API/`**: Core FastAPI backend managing PostgreSQL connections, user authentication (JWT), sessions, and device registration.\n")
            markdown_content.append("- **`Frontend/`**: React web application built with Vite and styled using vanilla CSS. Exposes live readings, history charts, theme switching, localization, and ratings.\n")
            markdown_content.append("- **`IOT/`**: Embedded C firmware designed for the ATmega2560 microcontroller to interface with sensors (DHT11, MH-Z19B, KY-018), buttons, display, and buzzer.\n")
            markdown_content.append("- **`MAL/`**: Machine Learning and API (MAL) Python service, deploying Random Forest and MLP neural network models for comfort suitability inference.\n")
            markdown_content.append("- **`initdb/`**: SQL schema initialization scripts for automatic PostgreSQL database container setup.\n\n")
            
    # 3. Read the original project report
    with open(report_file, 'r', encoding='utf-8') as f:
        content = f.read()
        
    # Find the "# Appendices" heading (case-insensitive, optional spaces)
    appendices_match = re.search(r"^\s*#\s+Appendices\s*$", content, re.IGNORECASE | re.MULTILINE)
    
    if not appendices_match:
        print("Error: Could not find '# Appendices' heading in the project report.")
        return
        
    # Keep everything up to the "# Appendices" line and replace the rest
    base_content = content[:appendices_match.start()]
    final_content = base_content + "".join(markdown_content)
    
    with open(report_file, 'w', encoding='utf-8') as f:
        f.write(final_content)
        
    print("Appendices section regenerated in project-report.md successfully.")

if __name__ == "__main__":
    generate_appendices()
