@base = https://mal.sep4.eduardfekete.com
@base2 = http://api.sep4.eduardfekete.com

### Hello
GET {{base}}/
Accept: application/json

### DB check
GET {{base}}/db-check
Accept: application/json

### Collect labeled sensor data
GET {{base}}/collect-data
Accept: application/json

### Model info
GET {{base}}/model-info
Accept: application/json

### Predict a focus rating from temperature
POST {{base}}/predict
Content-Type: application/json
Accept: application/json

{
  "currentTemperature": 22,
  "maxTemp": 24,
  "minTemp": 20,
  "meanTemp": 22
}

### Invalid prediction payload returns 422
POST {{base}}/predict
Content-Type: application/json
Accept: application/json

{
  "currentTemperature": 22,
  "maxTemp": 19,
  "minTemp": 20,
  "meanTemp": 22
}

### 
POST {{base2}}/instant-measurement
Content-Type: application/json
Accept: application/json

{
  "temperature": 21,
  "humidity": 10000,
  "co2Level": 1,
  "lightLevel": 10000
}

###
POST {{base}}/instant-predict
Content-Type: application/json
Accept: application/json

{
  "temperature": 21,
  "humidity": 3000,
  "co2Level": 500,
  "lightLevel": 10002,
  "noise": 29
}
